#!/usr/bin/env bash
#
# Summary: Show the current miner version 

set -e
[ -n "$MINER_DEBUG" ] && set -x

resolve_link() {
  $(type -p greadlink readlink | head -1) "$1"
}

if [ -z "$MINER_VERSION" ]; then
  if [ -f "$MINER_ROOT/versions/current" ]; then
    MINER_VERSION=$(resolve_link "$MINER_ROOT/versions/current")
  fi
fi

if [ -z "$MINER_VERSION" ]; then
  echo "system"
  exit
fi

version_exists() {
  local version="$1"
  [ -d "$MINER_ROOT/versions/$version" ]
}

if version_exists "$MINER_VERSION"; then
  echo $MINER_VERSION
else
  echo "miner: version \`$MINER_VERSION' not installed" >&2
  exit 1
fi
