#!/usr/bin/env bash

set -e
export -n CDPATH

if [ "$1" = "--debug" ]; then
  export MINER_DEBUG=1
  shift
fi

if [ -n "$MINER_DEBUG" ]; then
  export PS4='+ [${BASH_SOURCE##*/}:${LINENO}] '
  set -x
fi

READLINK=$(type -p greadlink readlink | head -1)
if [ -z "$READLINK" ]; then
  echo "rbenv: cannot find readlink - are you missing GNU coreutils?" >&2
  exit 1
fi

if [ -z "$MINER_ROOT" ]; then
  MINER_ROOT="$($READLINK -f "$(dirname $0)/../")"
fi
export MINER_ROOT

cd "$MINER_ROOT" 2>/dev/null || {
  echo "miner: cannot change working directory to \`$MINER_ROOT'"
}

export PATH="$MINER_ROOT/libexec:$PATH"

command="$1"
case "$command" in
"" | "-h" | "--help" )
  echo -e "$(miner---version)\n$(miner-help)" >&2
  ;;
"-v" )
  exec miner---version
  ;;
* )
  command_path="$(command -v "miner-$command" || true)"
  if [ -z "$command_path" ]; then
    echo "miner: no such command \`$command'" >&2
    exit 1
  fi

  shift 1
  exec "$command_path" "$@"
  ;;
esac
