#!/usr/bin/env bash
#
# Summary: Show the current miner version 

set -e
[ -n "$MINER_DEBUG" ] && set -x

new_version="$1"
if [ -z "$new_version" ]; then
  miner-version-name
  exit
fi

if [ "$new_version" = "system" ]; then
  rm -f "$MINER_ROOT/versions/current"
fi

if [ -d "$MINER_ROOT/versions/$new_version" ]; then
  rm -f "$MINER_ROOT/versions/current"
  cd "$MINER_ROOT/versions"
  ln -s "$new_version" "current"
else
  echo "miner: version \`$new_version' not installed" >&2
  exit 1
fi
