#!/usr/bin/env bash
#
# Summary: Show the current selected miner version

set -e
[ -n "$PICK_DEBUG" ] && set -x

resolve_link() {
  $(type -p greadlink readlink | head -1) "$1"
}

if [ -z "$PICK_VERSION" ] && [ -h "$PICK_ROOT/versions/current" ]; then
  PICK_VERSION=$(resolve_link "$PICK_ROOT/versions/current")
fi

if [ -z "$PICK_VERSION" ]; then
  echo "system"
  exit
fi

version_exists() {
  local version="$1"
  [ -d "$PICK_ROOT/versions/$version" ]
}

if version_exists "$PICK_VERSION"; then
  echo $PICK_VERSION
else
  echo "pick: version \`$PICK_VERSION' not installed" >&2
  exit 1
fi
